/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import database.database_functions;
import java.awt.Toolkit;
import java.awt.PrintJob;
import java.awt.Graphics;
import functions.iofunctions;
import javax.swing.JFrame;
import functions.datearray;
/**
 *
 * @author root
 */
public class printbill extends javax.swing.JFrame {

    /**
     * Creates new form printbill
     */
    static iofunctions io;
    static database_functions db;
    static int token;
    static datearray getdate;
    String entrymonth,entryyear,entrydate;
    public printbill() {
        initComponents();
         this.setLocationRelativeTo( null );
         this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         db = new database_functions();
         io = new iofunctions();
         getdate = new datearray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        bill = new javax.swing.JPanel();
        company = new javax.swing.JLabel();
        horsep1 = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        ghee = new javax.swing.JLabel();
        imilk = new javax.swing.JLabel();
        ighee = new javax.swing.JLabel();
        itotal = new javax.swing.JLabel();
        horsep2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        iremain = new javax.swing.JLabel();
        ipay = new javax.swing.JLabel();
        qmilk = new javax.swing.JLabel();
        qghee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rghee = new javax.swing.JLabel();
        rmilk = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        remain = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        tghee = new javax.swing.JLabel();
        tmilk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JLabel();
        issuemonth = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jButton1.setText("Print Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bill.setBackground(new java.awt.Color(255, 255, 255));
        bill.setBorder(javax.swing.BorderFactory.createTitledBorder("MILK BILL"));

        company.setFont(new java.awt.Font("Cantarell", 1, 26)); // NOI18N
        company.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        horsep1.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        horsep1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horsep1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        customer.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        customer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        ghee.setFont(new java.awt.Font("Cantarell", 0, 26)); // NOI18N
        ghee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ghee.setText("                 Quantity       Rates       Total");

        imilk.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        imilk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        imilk.setText("MILK");

        ighee.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        ighee.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ighee.setText("GHEE");

        itotal.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        itotal.setText("TOTAL");

        horsep2.setFont(new java.awt.Font("Cantarell", 0, 12)); // NOI18N
        horsep2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horsep2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        date.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        iremain.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        iremain.setText("REMAIN");

        ipay.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        ipay.setText("PAY");

        qmilk.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        qghee.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        rghee.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        rmilk.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        pay.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        remain.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        total.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        tghee.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        tmilk.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("GRAND TOTAL");

        grandtotal.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N

        issuemonth.setFont(new java.awt.Font("Cantarell", 0, 22)); // NOI18N
        issuemonth.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill);
        bill.setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ghee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horsep1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(company, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horsep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(billLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billLayout.createSequentialGroup()
                        .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ipay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iremain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(itotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ighee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imilk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(issuemonth, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(billLayout.createSequentialGroup()
                                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qghee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(qmilk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rghee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(remain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tghee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tmilk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horsep1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ghee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imilk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(qmilk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rmilk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tmilk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tghee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rghee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ighee, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qghee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iremain, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ipay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(issuemonth, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(horsep2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(grandtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthItemStateChanged(evt);
            }
        });
        month.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                monthInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                monthCaretPositionChanged(evt);
            }
        });
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(month, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(year))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void change()
    {
      try
      {
          int[] datadate = getdate.returndate();
         // month.setSelectedIndex(datadate[1]);
         // year.setSelectedIndex(datadate[2]-2018);
          date.setText(datadate[0]+"-"+datadate[1]+"-"+datadate[2]);
          entrymonth = month.getSelectedItem().toString();
          entryyear  = year.getSelectedItem().toString();
          entrydate = entrymonth+"-"+entryyear;
          
          io.o("\n"+entrydate+"\n");
          String[][] result = db.retrieve("select company from owner", 1);
          company.setText(result[0][0]);
          result = db.retrieve("select name from customer where token = '"+token+"'", 1);
          customer.setText("CUSTOMER  :  "+result[0][0]+"("+token+")");
          horsep1.setText("*************************************************************");
          horsep2.setText("*************************************************************");
          try
          {
             result = db.retrieve("select milkq,milkr,milkt,gheeq,gheer,gheet,"
                  + "old,total,pay,grand from record where token = '"+token+"' AND "
                          + "date = '"+entrydate+"' ", 10);
             qmilk.setText(" "+result[0][0]);
             rmilk.setText(" "+result[0][1]);
             tmilk.setText(" "+result[0][2]);
             qghee.setText(" "+result[0][3]);
             rghee.setText(" "+result[0][4]);
             tghee.setText(" "+result[0][5]);
             total.setText(" "+result[0][7]);
             remain.setText(" "+result[0][6]);
             pay.setText(" "+result[0][8]);
             grandtotal.setText(result[0][9]);
             issuemonth.setText(entrydate+" BILL");
          }
          catch(Exception e)
          {
              
          }
      }
      catch(Exception e)
      {
          
      }
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      try
      {
          int[] datadate = getdate.returndate();
          month.setSelectedIndex(datadate[1]);
          year.setSelectedIndex(datadate[2]-2018);
          date.setText(datadate[0]+"-"+datadate[1]+"-"+datadate[2]);
          entrymonth = month.getSelectedItem().toString();
          entryyear  = year.getSelectedItem().toString();
          entrydate = entrymonth+"-"+entryyear;
          String[][] result = db.retrieve("select company from owner", 1);
          company.setText(result[0][0]);
          result = db.retrieve("select name from customer where token = '"+token+"'", 1);
          customer.setText("CUSTOMER  :  "+result[0][0]+"("+token+")");
          horsep1.setText("*************************************************************");
          horsep2.setText("*************************************************************");
          try
          {
             result = db.retrieve("select milkq,milkr,milkt,gheeq,gheer,gheet,"
                  + "old,total,pay,grand from record where token = '"+token+"' AND "
                          + "date = '"+entrydate+"' ", 10);
             qmilk.setText(" "+result[0][0]);
             rmilk.setText(" "+result[0][1]);
             tmilk.setText(" "+result[0][2]);
             qghee.setText(" "+result[0][3]);
             rghee.setText(" "+result[0][4]);
             tghee.setText(" "+result[0][5]);
             total.setText(" "+result[0][7]);
             remain.setText(" "+result[0][6]);
             pay.setText(" "+result[0][8]);
             grandtotal.setText(result[0][9]);
             issuemonth.setText(entrydate+" BILL");
          }
          catch(Exception e)
          {
              
          }
      }
      catch(Exception e)
      {
          
      }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Toolkit tkp = bill.getToolkit();
       PrintJob pjp = tkp.getPrintJob(this, null, null);
       Graphics g = pjp.getGraphics();        
       try
        {
          bill.print(g);
        }
        catch(Exception e)
        {
          io.alert(e+"");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthItemStateChanged
      //  this.change();
    }//GEN-LAST:event_monthItemStateChanged

    private void monthInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_monthInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_monthInputMethodTextChanged

    private void monthCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_monthCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_monthCaretPositionChanged

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        this.change();
    }//GEN-LAST:event_monthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void show(int paratoken) {
        token = paratoken;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printbill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bill;
    private javax.swing.JLabel company;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel date;
    private javax.swing.JLabel ghee;
    private javax.swing.JLabel grandtotal;
    private javax.swing.JLabel horsep1;
    private javax.swing.JLabel horsep2;
    private javax.swing.JLabel ighee;
    private javax.swing.JLabel imilk;
    private javax.swing.JLabel ipay;
    private javax.swing.JLabel iremain;
    private javax.swing.JLabel issuemonth;
    private javax.swing.JLabel itotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel pay;
    private javax.swing.JLabel qghee;
    private javax.swing.JLabel qmilk;
    private javax.swing.JLabel remain;
    private javax.swing.JLabel rghee;
    private javax.swing.JLabel rmilk;
    private javax.swing.JLabel tghee;
    private javax.swing.JLabel tmilk;
    private javax.swing.JLabel total;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
